ALTER TABLE URUN ADD CONSTRAINT FK_STOK_URUN FOREIGN KEY (Stok_No) REFERENCES STOK(Stok_No);

ALTER TABLE URUN ADD CONSTRAINT FK_URUN_KATEGORI FOREIGN KEY (Kategori_ID) REFERENCES KATEGORI(Kategori_ID);

ALTER TABLE SIPARIS_DETAY ADD CONSTRAINT FK_SEHIR_SIPARIS_DETAY FOREIGN KEY (Sehir_Kodu) REFERENCES SEHIR(Sehir_Kodu);

ALTER TABLE ODEME ADD CONSTRAINT FK_MUSTERI_ODEME FOREIGN KEY (Musteri_ID) REFERENCES MUSTERI(Musteri_ID);

ALTER TABLE SIPARIS_DETAY ADD CONSTRAINT FK_URUN_SIPARIS_DETAY FOREIGN KEY (Urun_ID) REFERENCES URUN(Urun_ID);

ALTER TABLE URUN ADD CONSTRAINT FK_FIRMA_URUN FOREIGN KEY (Firma_ID) REFERENCES FIRMA(Firma_ID);

ALTER TABLE SIPARIS ADD CONSTRAINT FK_SIPARIS_DETAY_SIPARIS FOREIGN KEY (Siparis_Detay_ID) REFERENCES SIPARIS_DETAY(Siparis_Detay_ID);

ALTER TABLE SIPARIS ADD CONSTRAINT FK_MUSTERI_SIPARIS FOREIGN KEY (Musteri_ID) REFERENCES MUSTERI(Musteri_ID);